server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ratingService
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: RATING-SERVICE
