server:
  port: 8085

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id : USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path= /users/**

        - id: DEVICE-DETAILS
          uri: lb://DEVICE-DETAILS
          predicates:
            - Path= /devices/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path= /ratings/**
